services:
  - type: web
    name: igrejakerigma
    env: static
    staticPublishPath: ./meunomeprojeto
    buildCommand: ""
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "no-store"
