services:
  - type: web
    name: igrejakerigma
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: ADMIN_TOKEN
        value: troque-este-token
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "no-store"
